name: Validar Compilação no macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Compilar o Driver com o Makefile
      run: |
        make

    - name: Estruturar a Kext Corretamente
      run: |
        # Cria a árvore de pastas correta
        mkdir -p RTL8723BE.kext/Contents/MacOS
        
        # Copia os arquivos para dentro da estrutura
        cp Info.plist RTL8723BE.kext/Contents/
        cp RTL8723BE RTL8723BE.kext/Contents/MacOS/
        
        # Compacta a pasta inteira em um arquivo .zip real para o GitHub não espalhar os arquivos
        zip -r RTL8723BE.kext.zip RTL8723BE.kext/

    - name: Upload da Kext Compactada
      uses: actions/upload-artifact@v4
      with:
        name: RTL8723BE-Kext-Pronta
        path: RTL8723BE.kext.zip
