name: Validar Compilação no macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # Define o servidor como o macOS mais recente disponível no GitHub
    runs-on: macos-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Compilar o Driver com o Makefile
      run: |
        make

    - name: Estruturar a Kext Corretamente
      run: |
        # Cria a árvore de pastas correta: Kext -> Contents -> MacOS
        mkdir -p RTL8723BE.kext/Contents/MacOS
        
        # Move o arquivo de configuração (.plist) para a Contents
        mv Info.plist RTL8723BE.kext/Contents/
        
        # Move o executável binário final para a MacOS
        mv RTL8723BE RTL8723BE.kext/Contents/MacOS/

    - name: Upload da Kext Pronta
      uses: actions/upload-artifact@v4
      with:
        name: RTL8723BE-Kext-Pronta
        path: RTL8723BE.kext/
