name: Validar Compilação no macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # Define o servidor como o macOS mais recente disponível no GitHub
    runs-on: macos-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Compilar o Driver com o Makefile
      run: |
        make
        - name: Upload dos Arquivos da Kext
      uses: actions/upload-artifact@v4
      with:
        name: RTL8723BE-Driver-Vini
        path: |
          *.o
          Info.plist
